theme: jekyll-theme-minimal
thumbnail-img: https://github.com/GauthamKrishnaDas98/GauthamKrishnaDas98.github.io/blob/main/image/passport%20size.jpg
title: [Gautham's Portfolio]
url: "https://github.com/GauthamKrishnaDas98"
